In [1]:
import numpy as np

In [3]:
data = [1,2,3,4,5,6,7,8]
data = np.array(data)
print(data)
print(type(data))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [19]:
data = np.array([
    [10, 20, 30],
    [20, 4, 24],
    [30, 56, 80]
])

In [21]:
print(data[2,1])

56


In [23]:
print(data[0,])

[10 20 30]


In [25]:
print(data[:])

[[10 20 30]
 [20  4 24]
 [30 56 80]]


In [47]:
print(data[:,:2])
print(data[:,:-1])
print(data[:, 1])
print(data[:, -2])

[[10 20]
 [20  4]
 [30 56]]
[[10 20]
 [20  4]
 [30 56]]
[20  4 56]
[20  4 56]


In [53]:
split = 1
train = data[:split,:]
test = data[split:, :]
print(train)
print(test)

[[10 20 30]]
[[20  4 24]
 [30 56 80]]


In [63]:
data = np.array([
    [20,20,40, 5],
    [50, 10, 20, 25],
    [40, 4, 10, 55]]
                )

print(data.shape)

(3, 4)


In [57]:
rows = data.shape[0]  # Number of rows
columns = data.shape[1]
print(rows)
print(columns)

3
4


In [69]:
data = np.array([1,2,3,4,5])

print(data.shape)
# reshape
data = data.reshape((data.shape[0], 1))
print(data.shape)
print(data)

(5,)
(5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


In [71]:
data = np.array([1,2,3,4,5])

print(data.shape)
# reshape
data = data.reshape((data.shape[0], 2))
print(data.shape)
print(data)

(5,)


ValueError: cannot reshape array of size 5 into shape (5,2)

In [75]:
data = np.array([
    [10,20],
        [30,40],
        [50,60]
       ])

print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1],1))
print(data.shape)
print(data)

(3, 2)
(3, 2, 1)
[[[10]
  [20]]

 [[30]
  [40]]

 [[50]
  [60]]]


In [79]:
arr = np.array([10,20,30,40,50])
print(arr[2])
print(arr[-1])
print(arr[1:4])

30
50
[20 30 40]


In [83]:
data1 = [[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
data1 = np.array(data1)
print(data1[0,1])
print(data1[0])
print(data1[:, 1])

2
[1 2 3]
[2 5 8]


In [98]:
vector = np.array([1,2,3,4,5,6])
reshaped_vector = vector.reshape((2, 3))
print(reshaped_vector)
print(vector.shape)
original_vector = reshaped_vector.reshape(-1)
print(original_vector.shape)

[[1 2 3]
 [4 5 6]]
(6,)
(6,)


In [114]:
data2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])
x, y = data2[:, : 2], data2[: , 2]
print(x)
print(y)
print(x.shape)
print(y.shape)

[[10 20]
 [40 50]
 [70 80]]
[30 60 90]
(3, 2)
(3,)
